//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProiect2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialProperty
    {
        public int DataID { get; set; }
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyDescription { get; set; }

        public static SpecialProperty CreateSpecialProperty(string propertyName, string propertyDescription)
        {
            return new SpecialProperty
            {
                DataID = new Random().Next(1, 20000),
                PropertyID = new Random().Next(1, 20000),
                PropertyName = propertyName,
                PropertyDescription =propertyDescription
            };
        }
    }
}
