//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDesignFirst_L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int dataId { get; set; }
        public string dataType { get; set; }
        public System.TimeSpan creationDate { get; set; }
        public string eventName { get; set; }
        public string people { get; set; }
        public string location { get; set; }
        public string path { get; set; }
        public bool movedData { get; set; }
        public bool favoriteData { get; set; }
    }
}
