//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDesignFirst_L1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialProperties
    {
        public int dataId { get; set; }
        public string propertyID { get; set; }
        public string propertyName { get; set; }
        public string propertyDescription { get; set; }
    }
}
