//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProiect2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int DataID { get; set; }
        public string DateType { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string EventName { get; set; }
        public string People { get; set; }
        public string Location { get; set; }
        public string Path { get; set; }
        public bool MovedData { get; set; }
        public bool FavoriteData { get; set; }

        public static Data CreateData(string dateType, DateTime creationDate, string eventName, string people, string location,string path)
        {
            return new Data
            {
                DataID = new Random().Next(1, 20000),
                DateType = dateType,
                CreationDate = creationDate,
                EventName = eventName,
                People = people,
                Location = location,
                Path = path,
                MovedData =false,
                FavoriteData=true
            };
        }
    }
}
